### --

# GET - IES 

GET https://ies21.edu.ar/carreras 

### --

# GET - REST API

GET https://api.escuelajs.co/api/v1/users

### --

# GET localhost:3000
GET http://localhost:3000

### --

# GET localhost:3000
POST http://localhost:3000/guardar-datos
